name: gravitational_waves
description: This is a simple homage to Gravity Square, an old infinity runner discontinued by Kongregate.
version: 0.4.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  dartlin: ^0.6.3
  dio: ^5.5.0+1
  firebase_analytics: ^11.2.0
  firebase_core: ^3.2.0
  flame: ^1.18.0
  flame_audio: ^2.10.2
  flame_splash_screen: ^0.3.0
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0
  json_annotation: ^4.9.0
  oktoast: ^3.4.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.11
  dashbook: ^0.1.15
  flame_lint: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon_background.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
   - assets/firescore_uuid
   - assets/images/
   - assets/audio/music/
   - assets/audio/sfx/

  fonts:
   - family: Quantum
     fonts:
       - asset: assets/fonts/Quantum.otf

